language: go

go:
  - "1.14"

before_script:
  - psql -c "CREATE ROLE library WITH SUPERUSER LOGIN;" -U postgres
  - psql -c "CREATE DATABASE library;" -U postgres
  - psql -c "ALTER ROLE library WITH PASSWORD 'library';" -U library


script:
  - go run main.go & disown
  - sleep 5
  - go run cmd/tester.go

services:
  - postgresql
