language: go

go:
  - "1.14"

before_script:
  - psql -c "CREATE ROLE webserver WITH SUPERUSER LOGIN;" -U postgres
  - psql -c "CREATE DATABASE webserver;" -U postgres
  - psql -c "ALTER ROLE webserver WITH PASSWORD 'webserver';" -U webserver
  - go run main.go & disown

script:
  - go run cmd/tester.go

services:
  - postgresql
