language: go
go:
- "1.14"
before_script:
  - psql -c 'CREATE ROLE webserver WITH SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE webserver;' -U webserver
  - psql -c 'ALTER ROLE webserver WITH PASSWORD "webserver"' -U webserver
services:
  - postgresql
